### PR TITLE
Added check to ignore unexported struct fields in IsEmptyValue

### PR DESCRIPTION
**Pull request by allhailjarjar**
Unexported fields should be ignored as they will panic if ValueOf() is called on them

### CODE REVIEW

**Comment by anacrolix** [comment]
I wonder why it was done this way? Why is it failing for you now? Is a struct empty if we're ignoring its hidden fields that aren't empty?

**Comment by allhailjarjar** [comment]
My guess is it was an oversight since they just created the snippet to answer the question.
I was just looking at the stackoverflow link in the comment, and someone else also ran into the same issue: https://stackoverflow.com/a/27494761

But I like my solution more because it's more clear :) 


>Why is it failing for you now?

I had an unexported field in my struct, and it was extremely confusing why I was getting a panic when trying to marshal to bencode.



>Is a struct empty if we're ignoring its hidden fields that aren't empty?

That's a tricky one. We'd have to ask where and why would someone use this function `IsEmptyValue`. It will most likely be on a struct form some other package, and realistically, it would probably one be used when serializing some struct. And since unexported fields aren't accessible and shouldn't be serialized, i think the answer is the struct should be considered empty

**Comment by anacrolix** [comment]
Thanks for the thorough reply! What about using generics to create a zero value of the type being tested, and comparing to that?

**Comment by allhailjarjar** [comment]
I don't think you can create an instance of a generic type. However concrete types can be used as a parameter to types/functions that have a generic field. Think of generics as a placeholder used by the compiler to replace the generic type with the concrete type in the compiled output, and not as a value itself.

Even if you could somehow create a zero value with generics, that would have the same issue, because the reflect package would still not have access to the unexported fields

**Comment by anacrolix** [comment]
Where were you using this from? Was it in anacrolix/dht somewhere?

**Comment by anacrolix** [comment]
@allhailjarjar take a look at https://github.com/anacrolix/missinggo/compare/generic-zero-value?expand=1.

**Comment by allhailjarjar** [comment]
That's pretty clever!

I also just found this which does exactly what you want here: https://pkg.go.dev/reflect#DeepEqual where it says "Struct values are deeply equal if their corresponding fields, both exported and unexported, are deeply equal"

>Where were you using this from? Was it in anacrolix/dht somewhere?

Yes, I was. I don't completely remember, but I don't think I need it anymore, but others might run into issues with this panic error.

**Comment by anacrolix** [comment]
In truth, IsEmptyValue probably shouldn't exist because it's only used in one place and it's not really clear what the caller intends (whether they care about unexported values, uncomparable values, etc.). Consider even if you would consider []int{} and []int(nil) to be the same. Which is the zero value?

**Comment by anacrolix** [comment]
I will close this @allhailjarjar, the input was really appreciated. As mentioned above, the function shouldn't be used.

**Pull request closed without merging**
